name:                hdbcperf
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/hdbcperf#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - QuickCheck
  - time
  - odbc == 0.2.0
  - HDBC-odbc
  - split
  - HDBC 
  - text
  - bytestring

executables:
  hdbcperf:
    source-dirs:      src
    main:             Main.hs
    ghc-options:
    - -threaded
